"""
STEP 4.1-4.4 (quantized track, OFFLINE): replay from captures/q4_*/*.npy. No model.
Weights: Ollama qwen2.5:0.5b GGUF (file_type 15 = Q4_K_M), rope NeoX base 1e6, d=64.
- K files are UNROTATED (Kcur pre-RoPE, verified by attention-output gate)
- slow band NeoX-correct: dims [24..31]+[56..63]; as-coded contiguous [48..63] also scored
- sparsity 90/99/99.9 per layer/KV; bound gaps+split; prune @tau={16,8,4,2} w/ true local max
- violations counted (must be zero); CRQ 2-bit (+4-bit ref) output error
- CSV table generated by script. Watchdogs: 600 s/file, RSS 12 GB.
Usage: .venv/bin/python analyze_q4.py 2>&1 | tee logs/mzsae_q4_analyze.log
"""
import glob
import os
import sys
import time

import numpy as np

BLOCK = 32
D = 64
THETA = 1_000_000.0
TAUS = [16, 8, 4, 2]
T0_ALL = time.time()
RUNS = [("docA", 8192), ("docB", 8192), ("docC", 8192), ("docD", 8192),
        ("docA", 16384), ("docB", 16384), ("docC", 16384), ("docD", 16384),
        ("docA", 32768)]
if len(sys.argv) == 3:  # single-run mode for parallel .sh: analyze_q4.py docA 8192
    RUNS = [(sys.argv[1], int(sys.argv[2]))]
OUTCSV = ("logs/mzsae_q4_table.csv" if len(sys.argv) != 3
          else f"logs/rows_{sys.argv[1]}_{sys.argv[2]}.csv")


def log(m):
    print(f"[{time.strftime('%H:%M:%S')}] {m}", flush=True)


def rss_gb():
    import psutil
    return psutil.Process().memory_info().rss / 1e9


def watchdog(phase, t0):
    dt = time.time() - t0
    r = rss_gb()
    log(f"phase done: {phase} {dt:.1f}s rss={r:.2f}GB")
    if dt > 600:
        log(f"WATCHDOG: {phase} exceeded 600 s. STOPPING.")
        sys.exit(2)
    if r > 12:
        log(f"WATCHDOG: RSS {r:.2f}GB > 12 GB. STOPPING.")
        sys.exit(3)


INV = (THETA ** (-2.0 * np.arange(D // 2, dtype=np.float64) / D)).astype(np.float32)
SLOW_NEOX = np.concatenate([np.arange(24, 32), np.arange(56, 64)])
SLOW_CODED = np.arange(48, 64)
FAST_CODED = np.arange(0, 48)
FAST_NEOX = np.array([i for i in range(D) if i not in set(SLOW_NEOX.tolist())])
log(f"slow_neox={SLOW_NEOX.tolist()}")
log(f"slow_coded={SLOW_CODED.tolist()} equal_sets={set(SLOW_NEOX.tolist())==set(SLOW_CODED.tolist())}")
ISD = 1.0 / np.sqrt(D)


def unrope(x, pos, inv=INV):
    """Inverse NeoX rotation (captured K is post-RoPE; MZSAE needs unrotated)."""
    x = np.asarray(x, dtype=np.float64)
    p = np.asarray(pos, dtype=np.float64).reshape(-1, 1)
    a = p[..., None] * np.asarray(inv, dtype=np.float64)[None, :]
    c, s = np.cos(a), np.sin(a)
    x1, x2 = x[..., :32], x[..., 32:]
    return np.concatenate([x1 * c + x2 * s, -x1 * s + x2 * c], axis=-1).astype(np.float32)


def rope(x, pos, inv=INV):
    """Forward NeoX rotation (for CRQ-reconstructed pre-rope keys)."""
    x = np.asarray(x, dtype=np.float64)
    p = np.asarray(pos, dtype=np.float64).reshape(-1, 1)
    a = p[..., None] * np.asarray(inv, dtype=np.float64)[None, :]
    c, s = np.cos(a), np.sin(a)
    x1, x2 = x[..., :32], x[..., 32:]
    return np.concatenate([x1 * c - x2 * s, x2 * c + x1 * s], axis=-1).astype(np.float32)


def load_run(doc, n):
    d = f"captures/q4_{doc}_{n}"
    L = 24
    K = [np.load(f"{d}/L{il:02d}_K.npy") for il in range(L)]  # (T,kv,d) POST-rope
    V = [np.load(f"{d}/L{il:02d}_V.npy") for il in range(L)]
    Q = [np.load(f"{d}/L{il:02d}_Q.npy") for il in range(L)]  # (S,nh,d) POST-rope
    O = [np.load(f"{d}/L{il:02d}_O.npy") for il in range(L)]
    pos = np.loadtxt(f"{d}/positions.txt", dtype=str, delimiter="=")  # sanity only
    return K, V, Q, O


def crq2q(blk):
    c = blk.mean(0).astype(np.float64)
    r = blk.astype(np.float64) - c
    sc = max(float(np.abs(r).max()) / 1.5, 1e-7)
    nr = r / sc
    cd = np.zeros_like(nr, dtype=np.uint8)
    cd[nr < -1.0] = 0
    cd[(nr >= -1.0) & (nr < 0.0)] = 1
    cd[(nr >= 0.0) & (nr < 1.0)] = 2
    cd[nr >= 1.0] = 3
    return c.astype(np.float32), cd, np.float16(sc)


def crq2d(c, cd, sc):
    return (c.astype(np.float64) + (cd.astype(np.float64) - 1.5) * float(sc)).astype(np.float32)


def crq4(blk):
    c = blk.mean(0).astype(np.float64)
    r = blk.astype(np.float64) - c
    sc = max(float(np.abs(r).max()) / 7.0, 1e-9)
    return (c + np.clip(np.round(r / sc), -8, 7) * sc).astype(np.float32)


def main():
    log("=" * 70)
    log("OFFLINE Q4 ANALYSIS (Ollama qwen2.5:0.5b, Q4_K_M file_type=15)")
    log("=" * 70)
    rows = []
    for doc, n in RUNS:
        t0 = time.time()
        K, V, Q, O = load_run(doc, n)
        L = K[0].shape[0]
        NST = Q[0].shape[0]
        NHQ = Q[0].shape[1]
        NKV = K[0].shape[1]
        GQA = NHQ // NKV
        nB = (L + BLOCK - 1) // BLOCK
        pos = np.arange(L)
        log(f"--- {doc}@{n}: L={L} steps={NST} heads={NHQ}/{NKV} blocks={nB}")
        for li in range(24):
            # Captured K/Q are POST-RoPE (proven by token-duplicate + FP cross-check).
            # Dense scores use them as-is. Bound/CRQ inputs use UNROTATED K.
            Ku = unrope(K[li].astype(np.float64), pos)   # (L,kv,d) unrotated
            Ke = np.concatenate([K[li][:, g:g + 1, :].repeat(GQA, axis=1).astype(np.float64)
                                 for g in range(NKV)], axis=1)          # (L,14,d) post-rope
            Ku_e = np.concatenate([Ku[:, g:g + 1, :].repeat(GQA, axis=1)
                                   for g in range(NKV)], axis=1)        # (L,14,d) unrotated
            Kr = Ke
            Ve = np.concatenate([V[li][:, g:g + 1, :].repeat(GQA, axis=1)
                                 for g in range(NKV)], axis=1).astype(np.float64)
            # vectorized block stats per head (from UNROTATED keys, per MZSAE design):
            segs = [Ku_e[b * BLOCK:min((b + 1) * BLOCK, L)] for b in range(nB)]  # (tb,14,d)
            cents = np.stack([s.mean(0) for s in segs])                          # (nB,14,d)
            def R_of(slow):
                return np.stack([np.linalg.norm(s[:, :, slow] - c[None, :, slow], axis=2).max(0)
                                 for s, c in zip(segs, cents)])                   # (nB,14)
            def C_of(fast):
                return np.stack([np.linalg.norm(s[:, :, fast], axis=2).max(0)
                                 for s in segs])
            Rn = R_of(SLOW_NEOX)
            Rc = R_of(SLOW_CODED)
            Cn = C_of(FAST_NEOX)
            Cc = C_of(FAST_CODED)
            acc = {"c90": [], "c99": [], "c999": [], "g_n": [], "g_c": [],
                   "pr": {t: [0, 0] for t in TAUS}, "n": 0, "v_n": 0, "v_c": 0,
                   "ml": {t: 0.0 for t in TAUS},
                   "s_n": 0.0, "r_n": 0.0, "c_n": 0.0}
            prow_gate_me, prow_gate_co = float("nan"), float("nan")
            for j in range(NST):
                Qr = Q[li][j].astype(np.float64)                     # (14,d) post-rope as captured
                S = np.einsum("hd,lhd->hl", Qr, Kr) * ISD            # (14,L)
                Sm = S.max(1, keepdims=True)
                P = np.exp(S - Sm)
                P /= P.sum(1, keepdims=True)
                if j == NST - 1:  # validation gate vs model kqv_out
                    Or = np.einsum("hl,lhd->hd", P, Ve).astype(np.float32)
                    ref = O[li][j]
                    me = float(np.abs(Or - ref.astype(np.float64)).max())
                    co = float((Or * ref).sum() / (np.linalg.norm(Or.ravel())
                                                   * np.linalg.norm(ref.ravel()) + 1e-12))
                    log(f"{doc}@{n} L{li}: GATE maxerr={me:.3e} cos={co:.6f} (diagnostic; "
                        f"Q/K/V trust comes from FP cross-check, not this gate)")
                    prow_gate_me = me
                    prow_gate_co = co
                mt = S[:, max(0, L - 128):].max(1)
                bm = np.stack([P[:, b * BLOCK:min((b + 1) * BLOCK, L)].sum(1)
                               for b in range(nB)], axis=1)        # (14,nB)
                order = np.argsort(-bm, 1)
                cum = np.cumsum(np.take_along_axis(bm, order, 1), 1)
                for thr, k_ in ((0.90, "c90"), (0.99, "c99"), (0.999, "c999")):
                    acc[k_].append((np.argmax(cum >= thr, 1) + 1) / nB)
                bmax = np.stack([S[:, b * BLOCK:min((b + 1) * BLOCK, L)].max(1)
                                 for b in range(nB)], axis=1)
                for tag, slow, R, C in (("n", SLOW_NEOX, Rn, Cn), ("c", SLOW_CODED, Rc, Cc)):
                    qs = Qr[:, slow]
                    nqs = np.linalg.norm(qs, axis=1, keepdims=True)
                    U = (np.einsum("hd,bhd->hb", qs, cents[:, :, slow]) + nqs * R.T + C.T) * ISD
                    g = U - bmax
                    acc[f"g_{tag}"].append(g.ravel())
                    if tag == "n":
                        acc["s_n"] += float(np.einsum("hd,bhd->hb", qs, cents[:, :, slow]).mean() * ISD)
                        acc["r_n"] += float((nqs * R.T).mean() * ISD)
                        acc["c_n"] += float(C.mean() * ISD)
                        acc["v_n"] += int((g < -1e-3).sum())
                        for t_ in TAUS:
                            pr = U < (mt[:, None] - t_)
                            acc["pr"][t_][0] += int(pr.sum())
                            acc["ml"][t_] += float(bm[pr].sum())
                    else:
                        acc["v_c"] += int((g < -1e-3).sum())
                        for t_ in TAUS:
                            pr = U < (mt[:, None] - t_)
                            acc["pr"][t_][1] += int(pr.sum())
                acc["n"] += 14 * nB
                del S, P, Qr
            # CRQ on UNROTATED keys (MZSAE design); rotate reconstructions forward to score
            K2 = np.zeros_like(Ku_e)
            K4 = np.zeros_like(Ku_e)
            for b in range(nB):
                s0, s1 = b * BLOCK, min((b + 1) * BLOCK, L)
                for h in range(NHQ):
                    blk = Ku_e[s0:s1, h, :]
                    c2, cd2, sc2 = crq2q(blk)
                    assert cd2.size * 2 // 8 == 32 * D * 2 // 8
                    K2[s0:s1, h, :] = crq2d(c2, cd2, sc2)
                    K4[s0:s1, h, :] = crq4(blk)
            j = NST - 1
            Qr = Q[li][j].astype(np.float64)
            S = np.einsum("hd,lhd->hl", Qr, Kr) * ISD
            P = np.exp(S - S.max(1, keepdims=True))
            P /= P.sum(1, keepdims=True)
            Od = np.einsum("hl,lhd->hd", P, Ve)
            cr = {}
            for name, Kx in (("crq2", K2), ("crq4", K4)):
                Krx = rope(Kx.astype(np.float64), pos[:, None])
                Sx = np.einsum("hd,lhd->hl", Qr, Krx.astype(np.float64)) * ISD
                Px = np.exp(Sx - Sx.max(1, keepdims=True))
                Px /= Px.sum(1, keepdims=True)
                Ox = np.einsum("hl,lhd->hd", Px, Ve)
                df = np.abs(Ox - Od)
                co = float(((Ox * Od).sum(1) / (np.linalg.norm(Ox, 2, 1)
                                                * np.linalg.norm(Od, 2, 1) + 1e-12)).mean())
                cr[name] = (float(df.max()), float(df.mean()), co,
                            float((Sx.argmax(1) == S.argmax(1)).mean()))
            del Ke, Ku_e, Kr, Ve, K2, K4
            gn = np.concatenate(acc["g_n"])
            prow = {"run": f"{doc}@{n}", "layer": li}
            for k_, kk in (("c90", None), ("c99", None), ("c999", None)):
                prow[k_] = float(np.concatenate(acc[k_]).mean())
            prow.update(gap_mean=float(gn.mean()), gap_std=float(gn.std()),
                        gap_min=float(gn.min()), viol_neox=acc["v_n"] / acc["n"],
                        viol_coded=acc["v_c"] / acc["n"],
                        slow=float(acc["s_n"] / NST), resid=float(acc["r_n"] / NST),
                        cfast=float(acc["c_n"] / NST),
                        gate_me=float(prow_gate_me), gate_co=float(prow_gate_co))
            for t_ in TAUS:
                prow[f"prune{t_}"] = acc["pr"][t_][0] / acc["n"]
                prow[f"prune{t_}_coded"] = acc["pr"][t_][1] / acc["n"]
                prow[f"mloss{t_}"] = acc["ml"][t_] / (NST * NHQ)
            for name in ("crq2", "crq4"):
                mx, mn, co, a1 = cr[name]
                prow[f"{name}_max"] = mx
                prow[f"{name}_mean"] = mn
                prow[f"{name}_cos"] = co
                prow[f"{name}_top1"] = a1
            rows.append(prow)
            log(f"{doc}@{n} L{li}: c90={prow['c90']:.3f} c99={prow['c99']:.3f} c999={prow['c999']:.3f} "
                f"gap={prow['gap_mean']:+.2f}±{prow['gap_std']:.2f} violN={prow['viol_neox']*100:.2f}% "
                f"prune8={prow['prune8']*100:.1f}% mloss8={prow['mloss8']*100:.3f}% "
                f"crq2max={prow['crq2_max']:.2e} crq2top1={prow['crq2_top1']:.3f}")
        watchdog(f"run {doc}@{n}", t0)

    import csv
    with open(OUTCSV, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)
    log(f"table -> {OUTCSV} ({len(rows)} rows)")
    log("=" * 70)
    log("VERDICT (weights: Ollama qwen2.5:0.5b GGUF, Q4_K_M file_type=15)")
    ok = [r for r in rows if r["prune8"] > 0.50 and r["mloss8"] < 0.01 and r["viol_neox"] == 0.0]
    log(f"settings clearing (>50% pruned @tau=8, <1% mass lost, zero violations): {len(ok)}/{len(rows)}")
    for r in ok:
        log(f"  PASS: {r['run']} layer {r['layer']}")
    if not ok:
        log("BLOCK PRUNING IS NOT BENEFICIAL ON THIS MODEL. STOP.")


if __name__ == "__main__":
    main()
